# Configuration for Optikaii.
# Github: https://github.com/KaiijuMC/Optikaii

# Please don't change this!
version: 1

# How many ticks between AFK checks
afk-check-frequency: 20

# Per world configuration
world:
  default:
    # AFK settings
    afk-settings:
      # How many seconds before setting a player AFK
      duration: 120
      # Simulation distance settings
      simulation-distance:
        apply: true
        value: 10
      # View distance settings
      view-distance:
        apply: false
        value: 10