name: Kaiiview
version: ${version}
main: dev.kugge.kaiiview.Kaiiview
api-version: 1.19
authors: [kugge]
description: View distance for AFK players.
commands:
  opti:
    description: Kaiiview command
    usage: /<command>
    permission: kaiiview.command