name: Optikaii
version: ${version}
main: dev.kugge.optikaii.Optikaii
api-version: 1.19
authors: [kugge]
description: View distance for AFK players.
commands:
  opti:
    description: Optikaii command
    usage: /<command>
    permission: optikaii.command